name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build with dotnet
      run: dotnet build Rabbitmq.Tools.sln --configuration Release

    - name: Codecov
      uses: codecov/codecov-action@v1.0.5
      with:
        # User defined upload name. Visible in Codecov UI
        #name: # optional
        # Repository upload token - get it from codecov.io
        token: a7facff2-287e-401e-8619-a8b2b0b0909f
        # Path to coverage file to upload
        #file: # optional
        # Flag upload to group coverage metrics (e.g. unittests | integration | ui,chrome)
        #flags: # optional
        # Specify the location of the .codecov.yml config file
        #yml: # optional
        # Specify whether or not CI build should fail if Codecov runs into an error during upload
        #fail_ci_if_error: # optional
